config/routes.rb
Rails.application.routes.draw do
  # Priority: first created -> highest priority
  # Show all routes: "rake routes"

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'quick_search/member' => 'welcome#search_member'

  # Member Management
  resources :members do
    member do
      # put 'update_membership', as: 'update_membership_of'
    end
    collection do
      get 'moi_sheet', as: nil
      get 'email_list', as: nil
      get 'importer', as: nil, to: 'members_import#index'
      post 'importer/import', as: nil, to: 'members_import#import'
    end
    resources :memberships, only: [:index, :create, :destroy]
  end

  # User Session
  scope 'users', as: 'user' do
    resource :session, only: [:new, :create, :destroy],
                       controller: 'user_session'
  end

  # User Management
  resources :users

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= @page_title || I18n.t("nehsaa")
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default(role="navigation")
      .container-fluid
        .navbar-header
          button.navbar-toggle(type="button" data-toggle="collapse" data-target="#nehsaa-navigation-bar")
            span.sr-only Toggle Navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand(href="#{ root_path }") NEHSAA
        .collapse.navbar-collapse#nehsaa-navigation-bar
          ul.nav.navbar-nav
            li= link_to I18n.t("ui.about"), about_path
            li= link_to I18n.t("ui.member_management"), members_path
            li= link_to I18n.t("ui.user_management"), users_path
          ul.nav.navbar-nav.navbar-right
            li= user_session_link
    .container
      .row
        == breadcrumbs style: :bootstrap
      - if notice
        .row
          .alert.alert-info(role="alert")= notice
      - if alert
        .row
          .alert.alert-danger(role="alert")= alert
    = yield