config/routes.rb
Rails.application.routes.draw do
  # Priority: first created -> highest priority
  # Show all routes: "rake routes"

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'quick_search/member' => 'welcome#search_member'

  # Member Management
  resources :members do
    member do
      # put 'update_membership', as: 'update_membership_of'
    end
    collection do
      get 'moi_sheet', as: nil
      get 'email_list', as: nil
      get 'importer', as: nil, to: 'members_import#index'
      post 'importer/import', as: nil, to: 'members_import#import'
    end
    resources :memberships, only: [:index, :create, :destroy]
  end

  # User Session
  scope 'users', as: 'user' do
    resource :session, only: [:new, :create, :destroy],
                       controller: 'user_session'
  end

  # User Management
  resources :users

end

app/models/member.rb
class Member < ActiveRecord::Base
  extend Enumerize

  # Name
  validates :name, presence: true

  # Security ID
  validates :security_id, presence: true,
                          uniqueness: true,
                          security_id: true

  # Birthdate
  validates :birthdate, presence: true

  # Gender
  enumerize :gender, in: { male: 1, female: 2, other: 3 }
  validates :gender, presence: true

  # Member Type & Permanent
  enumerize :member_type, in: {
    normal_member: 1,
    teacher_member: 2,
    honor_member: 3
  }
  validates :member_type, presence: true
  validates :permanent, inclusion: { in: [true, false] }

  # Email
  validates :emails, presence: true
  validates_each :emails do |record, attribute, value|
    unless value.map{|v| ValidateEmail.valid?(v) }.reduce(:&)
      record.errors.add attribute, I18n.t(:invalid, :scope => "valid_email.validations.email")
    end
  end

  # Phone
  validates :phones, presence: true

  # Address
  validates :address, presence: true

  # Other Basic Info
  validates :occupation, :company, :education,
            { presence: true }
  # facebook can be blank

  # Association: memberships
  has_many :memberships, dependent: :delete_all

  # Graduation Information
  enumerize :grad_department, in: {
    kindergarten: 1,
    elementary: 2,
    junior_high: 3,
    senior_high: 4,
    bilingual: 5
  }
  # grad_class
  # grad_year
  # grad_id

  before_validation do
    emails.map!(&:strip).reject!(&:blank?)
    phones.map!(&:strip).reject!(&:blank?)
  end

  def age(date = Date.today)
    date.year - birthdate.year
  end

  def membership?(date = Date.today)
    flag = memberships.count > 0
    if flag
      flag = memberships.order(year: :asc).last.year >= (date.year - 2)
    end
    valid? && (age(date) < 20 || flag || permanent)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def index
    @members = Member.all.includes(:memberships)
    @member_grid = initialize_grid(@members)
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
    if @member.valid?
      redirect_to action: 'show', id: @member.id
    else
      render action: 'new'
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.update(params[:id], member_params)
    if @member.valid?
      redirect_to action: 'show', id: @member.id
    else
      render action: 'edit'
    end
  end

  def destroy
    Member.destroy(params[:id])
    redirect_to action: 'index'
  end

  def moi_sheet
    @members = Member.all
  end

  def email_list
    @members = Member.all
  end

  private

  def allowed_attributes
    unless defined? @allowed_attributes
      attribs = %i(name security_id birthdate gender
      occupation company education
      address facebook
      grad_class grad_year grad_id grad_department)
      attribs += %i(member_type permanent) # TODO: permission?
      attribs << { emails: [] }
      attribs << { phones: [] }
      @allowed_attributes = attribs
    end
    @allowed_attributes
  end

  def member_params
    unless @member_params
      @member_params = params.require(:member)
      @member_params = @member_params.permit(*allowed_attributes)
    end
    @member_params
  end

end

app/views/members/_form.html.slim
= simple_form_for @member do |f|
  = f.input :name
  = f.input :security_id
  = f.input :gender, as: :radio_buttons
  = f.input :birthdate, as: :string, placeholder: 'yyyy-mm-dd'
  = f.input :member_type, as: :radio_buttons
  = f.input :permanent
  = f.input :emails, as: :array, min_count: 2
  = f.input :phones, as: :array, min_count: 2
  = f.input :address
  = f.input :occupation
  = f.input :company
  = f.input :education
  = f.input :facebook
  = f.input :grad_class
  = f.input :grad_department, as: :radio_buttons
  = f.input :grad_year
  = f.input :grad_id
  = f.button :submit

app/views/members/edit.html.slim
- breadcrumb :edit_member, @member
.container
  .row
    = render "form"

app/views/members/email_list.html.slim
- breadcrumb :members_email_list
.container
  - @members.find_in_batches(batch_size: 500) do |batch|
    .row
      .panel.panel-default
        .panel-body
          p= batch.map{|m| m.emails.join(', ') }.join(', ')

app/views/members/index.html.slim
- breadcrumb :members
.container
  .row
    .panel.panel-default
      .panel-body
        = link_to new_member_path, class: 'btn btn-default' do
          = I18n.t("ui.members.new")
          span.glyphicon.glyphicon-plus
        = link_to({controller: :members, action: :moi_sheet}, {class: "btn btn-default"}) do
          = I18n.t('ui.members.moi_sheet')
          span.glyphicon.glyphicon-list-alt
        = link_to({controller: :members, action: :email_list}, {class: "btn btn-default"}) do
          = I18n.t('ui.members.email_list')
        = link_to({controller: :members_import, action: :index}, {class: "btn btn-default"}) do
          = I18n.t('ui.members.import')
  .row
    == grid(@member_grid, show_filters: :always) do |g|
      - g.column(name: 'ID', attribute: 'id', filter: false) do |m|
        - link_to(m.id, member_path(m))
      - g.column(name: Member.human_attribute_name('name'), attribute: 'name') do |m|
        - link_to(m.name, member_path(m))
      - g.column(name: Member.human_attribute_name('gender'), attribute: 'gender', filter: false) do |m|
        - m.gender.text
      - g.column(name: Member.human_attribute_name('birthdate'), attribute: 'birthdate', filter: false)  do |m|
        - I18n.l m.birthdate, format: :long
      - g.column(name: Member.human_attribute_name('security_id'), attribute: 'security_id')
      - g.column(name: Member.human_attribute_name('member_type'), attribute: 'member_type', filter: false) do |m|
        - m.member_type.text
      - g.column(name: Member.human_attribute_name('membership?')) do |m|
        - I18n.t(m.membership? ? 'yes' : 'no')
      - g.column(name: Member.human_attribute_name('valid?')) do |m|
        - I18n.t(m.valid? ? 'yes' : 'no')
      - g.column do |m|
        - link_to(edit_member_path(m)) do
          span.glyphicon.glyphicon-pencil
          span= I18n.t("ui.edit")

app/views/members/moi_sheet.html.slim
- breadcrumb :members_moi_sheet
table
  thead
    tr
      th= Member.human_attribute_name('name')
      th= Member.human_attribute_name('gender')
      th= Member.human_attribute_name('birthdate')
      th= Member.human_attribute_name('education')
      th= Member.human_attribute_name('occupation')
      th= Member.human_attribute_name('address')
      th= Member.human_attribute_name('phones')
      th= Member.human_attribute_name('comments')
  tbody
    - @members.find_each.select(&:membership?).each do |m|
      tr
        td= m.name
        td= m.gender.text
        td= I18n.l m.birthdate, format: :long
        td= m.education
        td= m.occupation
        td= m.address
        td= m.phones.join(', ')
        td

app/views/members/new.html.slim
- breadcrumb :new_member
.container
  .row
    = render "form"

app/views/members/show.html.slim
- breadcrumb :member, @member
.container
  .row
    .panel.panel-default
      .panel-body
        = link_to edit_member_path(@member), class: 'btn btn-primary' do
          = I18n.t("ui.edit")
          span.glyphicon.glyphicon-pencil
        = link_to member_memberships_path(@member), class: 'btn btn-default' do
            = Membership.model_name.human
            span.glyphicon.glyphicon-list-alt
        = link_to member_path(@member), class: 'btn btn-danger pull-right', method: :delete, data: {confirm: I18n.t("ui.confirm_delete")} do
          = I18n.t("ui.delete")
          span.glyphicon.glyphicon-trash
  .row
    .col-md-6.bg-info
      h1.text-center= I18n.t "ui.members.basic_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'name'
        .col-xs-8
          p= @member.name
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'gender'
        .col-xs-8
          p= @member.gender.text
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'birthdate'
        .col-xs-8
          p= I18n.l @member.birthdate, format: :long
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'security_id'
        .col-xs-8
          p= @member.security_id
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'education'
        .col-xs-8
          p= @member.education
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'occupation'
        .col-xs-8
          p= @member.occupation
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'company'
        .col-xs-8
          p= @member.company
    .col-md-6.bg-success
      h2.text-center= I18n.t "ui.members.contact_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'emails'
        .col-xs-8
          p= @member.emails.join(', ')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'phones'
        .col-xs-8
          p= @member.phones.join(', ')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'address'
        .col-xs-8
          p= @member.address
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'facebook'
        .col-xs-8
          p= @member.facebook
  .row
    .col-md-6
      h2.text-center= I18n.t "ui.members.graduation_info"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_class'
        .col-xs-8
          p= @member.grad_class
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_year'
        .col-xs-8
          p= @member.grad_year
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_id'
        .col-xs-8
          p= @member.grad_id
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'grad_department'
        .col-xs-8
          p= @member.grad_department && @member.grad_department.text
    .col-md-6.bg-warning
      h2.text-center= I18n.t "ui.members.membership_status"
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'member_type'
        .col-xs-8
          p= @member.member_type.text
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'permanent'
        .col-xs-8
          p= I18n.t(@member.permanent ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'membership?'
        .col-xs-8
          p= I18n.t(@member.membership? ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Member.human_attribute_name 'valid?'
        .col-xs-8
          p= I18n.t(@member.valid? ? 'yes' : 'no')
      .row
        .col-xs-4
          p.text-right= Membership.model_name.human
        .col-xs-6
          = link_to member_memberships_path(@member) do
            = I18n.t("ui.list")
            span.glyphicon.glyphicon-list-alt